const imageData = [
  {
    id: 1,
    src: './src/assets/images/image1.jpg',
    alt: 'Design 1',
    designName: 'Luncheonette Food Packaging Branding',
    designerName: 'Beth Mathews',
    tags: ['vintage restaurant', 'tomato', 'tomatoes', 'vintage packaging', 'packaging design', 'can design', 'sardine', 'fish packaging', 'tuna', 'olive oil', 'cans', 'canned food', 'food branding', 'food packaging', 'branding', 'vintage design', 'retro', 'wes anderson', 'vintage'],
    categories: ['Discover', 'Branding', 'Product Design'],
    colors: ['red', 'blue', 'beige'],
    likes: 150,
    views: 1200
  },
  {
    id: 2,
    src: './src/assets/images/image2.png',
    alt: 'Design 2',
    designName: 'Simms Fishing Apparel Design',
    designerName: 'Kevin Kronebruger',
    tags: ['print', 'type', 'retro', 'vintage', 'heritage', 'badge', 'patch', 'hat design', 'custom lettering', 'fly shop', 'logo design', 'logo designer', 'branding', 'apparel designer', 'apparel design', 'lettering', 'bozeman', 'montana', 'fly fishing', 'simms fishing'],
    categories: ['Discover', 'Product Design', 'Branding', 'Animation', 'Illustration', 'Typography'],
    colors: ['brown', 'orange'],
    likes: 200,
    views: 1800
  },
  {
    id: 3,
    src: './src/assets/images/image3.png',
    alt: 'Design 3',
    designName: 'Girl Illustration',
    designerName: 'Illustration Eonni',
    tags: ['hair', 'beauty', 'beautiful girl', 'portrait art', 'eyes', 'lips', 'yang lady', 'brunette', 'digital art', 'procreate', 'portrait', 'clouds', 'woman', 'girl', 'vector', 'graphic design', 'art', 'illustrator', 'illustration'],
    categories: ['Discover', 'Illustration', 'Animation'],
    colors: ['white', 'red', 'pink'],
    likes: 300,
    views: 2500
  },
  {
    id: 4,
    src: './src/assets/images/image4.png',
    alt: 'Design 4',
    designName: 'Heart of Africa',
    designerName: 'Folio Illustration Agency',
    tags: ['editorial', 'conservation', 'owen davey', 'flat', '2d', 'africa', 'zoo', 'nature', 'animals', 'vector', 'folioart', 'digital', 'illustration'],
    categories: ['Discover', 'Photography', 'Animation', 'Illustration'],
    colors: ['red', 'brown', 'white', 'yellow', 'orange'],
    likes: 250,
    views: 2100
  },
  {
    id: 5,
    src: './src/assets/images/image5.png',
    alt: 'Design 5',
    designName: 'La Palma Branding & Packaging Design',
    designerName: 'Mustafa Akülker',
    tags: ['product design', 'custom typography', 'graphic design', 'visual identity', 'craft roasted', 'specialty coffee', 'product branding', 'elegant design', 'green palette', 'modern typography', 'packaging design', 'artisan coffee', 'coffee label design', 'vietnamese coffee', 'small batch coffee', 'la palma coffee', 'espresso italiano', 'branding', 'minimalist design', 'coffee packaging'],
    categories: ['Discover', 'Branding', 'Print', 'Product Design', 'Typography'],
    colors: ['white', 'green', 'cyan', 'turquoise'],
    likes: 180,
    views: 1600
  },
  {
    id: 6,
    src: './src/assets/images/image6.png',
    alt: 'Design 6',
    designName: 'PLASTIC',
    designerName: 'Ada Vishneva',
    tags: ['graphic', 'creative', 'art illustration', 'design', 'artists', 'illustration', 'social', 'bag', 'cap', 'eco', 'pollution', 'plastic'],
    categories: ['Discover', 'Graphic Design', 'Animation', 'Illustration'],
    colors: ['red', 'blue', 'white', 'green', 'yellow', 'orange'],
    likes: 220,
    views: 2000
  },
  {
    id: 7,
    src: './src/assets/images/image7.png',
    alt: 'Design 7',
    designName: 'Smoke City',
    designerName: 'Dan Gartman',
    tags: ['town', 'city', 'texture', 'mixedmedia', 'gouache', 'art', 'drawing', 'illustration'],
    categories: ['Discover', 'Animation', 'Illustration'],
    colors: ['brown', 'white', 'orange', 'grey'],
    likes: 170,
    views: 1400
  },
  {
    id: 8,
    src: './src/assets/images/image8.png',
    alt: 'Design 8',
    designName: 'Dragon',
    designerName: 'Razvan Vezeteu',
    tags: ['funny', 'dragon', 'branding', 'ui', 'design', 'icon', 'retro', 'line', 'minimal', 'simple', 'graphic design', 'illustration'],
    categories: ['Discover', 'Illustration', 'Animation', 'Illustration'],
    colors: ['green', 'cyan'],
    likes: 280,
    views: 2300
  },
  {
    id: 9,
    src: './src/assets/images/image9.png',
    alt: 'Design 9',
    designName: 'Absolut Limited Edition',
    designerName: 'Simon Ålander',
    tags: ['simon ålander', 'coffee made me do it', 'vodka', 'absolut', 'packaging design', 'illustration', 'hand drawn', 'lettering', 'type', 'typography'],
    categories: ['Discover', 'Graphic Design', 'Branding', 'Animation', 'Illustration', 'Product Design'],
    colors: ['red', 'blue', 'green'],
    likes: 310,
    views: 2700
  },
  {
    id: 10,
    src: './src/assets/images/image10.png',
    alt: 'Design 10',
    designName: 'Halloween Icons',
    designerName: 'Elmira Gokoryan',
    tags: ['wizard', 'funny', 'cartoon', 'magic', 'icons', 'pumpkin', 'halloween', 'hat', 'broom', 'witch', 'vector', 'cute', 'illustration'],
    categories: ['Discover', 'Illustration', 'Animation'],
    colors: ['red', 'purple', 'orange'],
    likes: 190,
    views: 1700
  },
  {
    id: 11,
    src: './src/assets/images/image11.png',
    alt: 'Design 11',
    designName: 'Happy Logos | AI and crypto logos',
    designerName: 'Oleg Coada',
    tags: ['illustration', 'design', 'logotype', 'identity', 'logo design', 'logo robot', 'logo smile', 'blockchain visual identity', 'blockchain', 'ai branding', 'ai logo', 'crypto logo', 'logo'],
    categories: ['Discover', 'Graphic Design', 'Animation', 'Illustration'],
    colors: ['black', 'green', 'purple'],
    likes: 240,
    views: 2100
  },
  {
    id: 12,
    src: './src/assets/images/image12.png',
    alt: 'Design 12',
    designName: 'Golf Character',
    designerName: 'Victor Korchuk for Unfold',
    tags: ['vintage', 'mascot', 'character', 'green', 'fore', 'bogey', 'golfer', 'golf', 'logo', 'ui', 'branding', 'people', 'flat', 'design', 'figma', 'simple', 'clean', 'illustration'],
    categories: ['Discover', 'Illustration', 'Branding', 'Print', 'Product Design', 'Typography'],
    colors: ['green', 'beige'],
    likes: 260,
    views: 2300
  },
  {
    id: 13,
    src: './src/assets/images/image13.png',
    alt: 'Design 13',
    designName: 'Mobile App',
    designerName: 'Ronas IT | UI/UX Team',
    tags: ['design', 'mobile app design', 'mobile design', 'mobile app', 'app', 'mobile','phone'],
    categories: ['Discover', 'Mobile', 'Product Design'],
    colors: ['blue'],
    likes: 210,
    views: 1900
  },
  {
    id: 14,
    src: './src/assets/images/image14.png',
    alt: 'Design 14',
    designName: 'Coaching App',
    designerName: 'Lorenzo Perniciaro',
    tags: ['minimal', 'colors', 'schedule', 'habits', 'coach', 'design', 'app', 'ui'],
    categories: ['Discover', 'Graphic Design', 'Mobile', 'Product Design','phone'],
    colors: ['green'],
    likes: 230,
    views: 2000
  },
  {
    id: 15,
    src: './src/assets/images/image15.png',
    alt: 'Design 15',
    designName: 'Grocery List App Concept',
    designerName: 'Isabella Martinez',
    tags: ['purple', 'food', 'mobile app', 'menu', 'dark mode'],
    categories: ['Discover', 'Graphic Design', 'Mobile', 'Product Design','phone'],
    colors: ['purple', 'cyan', 'pink'],
    likes: 250,
    views: 2200
  },
  {
    id: 16,
    src: './src/assets/images/image16.png',
    alt: 'Design 16',
    designName: 'Girl in sea',
    designerName: 'Ethan Taylor',
    tags: ['colorful', 'vibrant', 'magic', 'mystic', 'book', 'plants', 'nature', 'bird', 'character', 'design', 'procreate', 'drawing', 'illustration', 'fish', 'ocean', 'sea'],
    categories: ['Discover', 'Illustration', 'Animation'],
    colors: ['blue', 'brown', 'white'],
    likes: 300,
    views: 2500
  },
  {
    id: 17,
    src: './src/assets/images/image17.png',
    alt: 'Design 17',
    designName: 'GOAT Product Page',
    designerName: 'Ava Harris',
    tags: ['product', 'goat', 'ecommerce', 'fashion', 'sneakers', 'shoes', 'motion', 'ui', 'mobile', 'design', 'ux'],
    categories: ['Discover', 'Graphic Design', 'Product Design', 'Web Design'],
    colors: ['brown', 'white', 'black'],
    likes: 280,
    views: 2400
  },
  {
    id: 18,
    src: './src/assets/images/image18.png',
    alt: 'Design 18',
    designName: 'The Row - Fashion Shop Ecommerce Website',
    designerName: 'Alexander Clark',
    tags: ['collection page', 'collection', 'minimalist', 'case study', 'website designer', 'ui', 'ux', 'website', 'website design', 'website layout', 'web design', 'modern', 'clean', 'fashion', 'clothing', 'ecommerce', 'online shop', 'luxury', 'awwwards', 'shopify'],
    categories: ['Discover', 'Product Design', 'Web Design'],
    colors: ['brown', 'white', 'black'],
    likes: 260,
    views: 2300
  },
  {
    id: 19,
    src: './src/assets/images/image19.png',
    alt: 'Design 19',
    designName: 'Pet Store Website Design',
    designerName: 'tubix UX',
    tags: ['website illustration', 'ecommerce', 'pet shop', 'pet store', 'pets', 'dogs', 'web page', 'user interface', 'user experience', 'interface', 'graphic design', 'web design', 'web', 'design', 'branding', 'ux', 'ui', 'illustration'],
    categories: ['Discover', 'Branding', 'Print', 'Product Design', 'Web Design'],
    colors: ['green', 'brown', 'lavender', 'beige'],
    likes: 210,
    views: 1900
  },
  {
    id: 20,
    src: './src/assets/images/image20.png',
    alt: 'Design 20',
    designName: 'Christian Dior',
    designerName: 'Benjamin Walker',
    tags: ['animation', 'web', 'ux', 'design', 'ui'],
    categories: ['Discover', 'Branding', 'Print', 'Product Design', 'Typography', 'Web Design'],
    colors: ['black', 'white'],
    likes: 300,
    views: 2500
  }
];

export default imageData;
